#!/bin/bash
export OUTPUTDIRROOT=/home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV
export CONFIGUREROOT=/home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/configure
export CONFIGUREDATAROOT=/home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/configure/data
export LOGFILEROOT=/home/wuc/MyWorkArea/g4sim/runlog/logfile.txt
export MATERIALLISTROOT=material_list.txt
export GEOCARDROOT=geometry_ProductionTarget.txt
export MAGFIELDCARDROOT=MagField_5T.txt
export GENFILEROOT=gen_ProductionTarget.txt
export OUTCARDROOT=output_ProductionTarget.txt
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/0_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/0_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/0_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/1_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/1_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/1_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/2_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/2_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/2_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/3_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/3_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/3_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/4_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/4_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/4_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/5_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/5_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/5_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/6_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/6_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/6_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/7_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/7_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/7_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/8_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/8_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/8_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/9_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/9_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/9_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/10_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/10_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/10_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/11_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/11_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/11_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/12_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/12_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/12_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/13_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/13_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/13_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/14_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/14_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/14_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/15_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/15_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/15_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/16_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/16_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/16_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/17_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/17_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/17_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/18_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/18_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/18_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/19_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/19_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/19_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/20_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/20_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/20_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/21_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/21_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/21_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/22_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/22_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/22_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/23_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/23_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/23_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/24_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/24_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/24_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/25_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/25_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/25_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/26_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/26_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/26_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/27_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/27_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/27_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/28_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/28_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/28_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/29_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/29_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/29_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/30_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/30_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/30_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/31_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/31_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/31_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/32_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/32_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/32_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/33_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/33_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/33_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/34_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/34_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/34_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/35_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/35_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/35_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/36_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/36_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/36_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/37_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/37_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/37_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/38_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/38_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/38_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/39_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/39_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/39_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/40_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/40_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/40_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/41_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/41_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/41_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/42_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/42_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/42_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/43_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/43_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/43_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/44_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/44_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/44_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/45_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/45_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/45_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/46_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/46_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/46_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/47_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/47_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/47_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/48_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/48_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/48_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/49_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/49_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/49_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/50_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/50_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/50_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/51_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/51_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/51_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/52_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/52_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/52_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/53_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/53_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/53_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/54_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/54_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/54_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/55_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/55_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/55_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/56_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/56_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/56_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/57_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/57_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/57_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/58_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/58_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/58_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/59_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/59_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/59_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/60_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/60_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/60_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/61_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/61_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/61_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/62_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/62_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/62_simulateError.txt &
nohup /home/wuc/MyWorkArea/g4sim/g4sim /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/macros/63_ProductionTarget.mac > /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/63_simulateLog.txt 2> /home/wuc/MyWorkArea/Data/raw/g4sim/ProductionTarget_C100GeV/63_simulateError.txt &
